export const lightThemeColors = {
  '--base-tone': '#ededed',
  '--tone-dim': '#e8e9e9',
  '--tone': '#dee5ed',
  '--ink': '#101624',
  '--ink-soft': '#636a76',
  '--ink-alt': '#ffffff',
  '--accent': '#3679e4',
  '--accent-dim': '#c3c7cb',
  '--harmonic': '#d6d8dc',
  '--harmonic-minor': '#e1e2e4',
  '--charged': '#f9699a',
  '--active': '#f4c762',
  '--calm': '#9ed999',
  '--still': '#9c81ec',
  '--charged-wash': 'color-mix(in oklch, var(--charged) 15%, var(--base-tone))',
  '--active-wash': 'color-mix(in oklch, var(--active)  15%, var(--base-tone))',
  '--calm-wash': 'color-mix(in oklch, var(--calm)    15%, var(--base-tone))',
  '--still-wash': 'color-mix(in oklch, var(--still)   15%, var(--base-tone))',
  '--shadow-color': 'rgba(0, 0, 0, 0.25)',
};

export const darkThemeColors = {
  '--base-tone': '#0f131b',
  '--tone-dim': '#121720',
  '--tone': '#162e48',
  '--ink': '#d3eaf8',
  '--ink-soft': '#6f8fa4',
  '--ink-alt': '#ffffff',
  '--accent': '#4cbef2',
  '--accent-dim': '#3d6178',
  '--harmonic': '#203d5d',
  '--harmonic-minor': '#162738',
  '--charged': '#f9699a',
  '--active': '#f4c762',
  '--calm': '#9ed999',
  '--still': '#9c81ec',
  '--charged-wash': 'color-mix(in oklch, var(--charged) 15%, var(--base-tone))',
  '--active-wash': 'color-mix(in oklch, var(--active)  15%, var(--base-tone))',
  '--calm-wash': 'color-mix(in oklch, var(--calm)    15%, var(--base-tone))',
  '--still-wash': 'color-mix(in oklch, var(--still)   15%, var(--base-tone))',
  '--shadow-color': 'rgba(0, 0, 0, 0.4)',
};

export const darkThemeColorsB = {
  '--base-tone': '#1f2937',
  '--tone-dim': '#374151',
  '--tone': 'rgba(59, 130, 246, 0.2)',
  '--ink': '#f3f4f6',
  '--ink-soft': '#9ca3af',
  '--ink-alt': '#ffffff',
  '--accent': '#60a5fa',
  '--accent-dim': '#4b5563',
  '--harmonic': 'blue',
  '--harmonic-minor': 'red',
  '--shadow-color': 'rgba(0, 0, 0, 0.4)',
  '--charged': '#f9699a',
  '--active': '#f4c762',
  '--calm': '#9ed999',
  '--still': '#9c81ec',
  '--charged-wash': 'color-mix(in oklch, var(--charged) 15%, var(--base-tone))',
  '--active-wash': 'color-mix(in oklch, var(--active)  15%, var(--base-tone))',
  '--calm-wash': 'color-mix(in oklch, var(--calm)    15%, var(--base-tone))',
  '--still-wash': 'color-mix(in oklch, var(--still)   15%, var(--base-tone))',
};