// Acera

export const lightThemeColors = {
  '--base-tone': '#e0e0e0',
  '--tone-dim': '#e8e6e6',
  '--tone': '#eac8bd',
  '--ink': '#25120d',
  '--ink-soft': '#5d4f4b',
  '--ink-alt': '#ffffff',
  '--accent': '#c2492a',
  '--accent-dim': '#e46845',
  '--harmonic': '#e2aea2',
  '--harmonic-minor': '#eed1ca',
  '--charged':   '#d1431f',
  '--active':    '#df8e01',
  '--calm':      '#00ad54',
  '--still':     '#2d5ae1',
  '--charged-wash': 'color-mix(in oklch, var(--charged) 15%, var(--base-tone))',
  '--active-wash': 'color-mix(in oklch, var(--active)  15%, var(--base-tone))',
  '--calm-wash': 'color-mix(in oklch, var(--calm)    15%, var(--base-tone))',
  '--still-wash': 'color-mix(in oklch, var(--still)   15%, var(--base-tone))',
};

export const darkThemeColors = {
  '--base-tone': '#62666a',
  '--tone-dim': '#6a6e6e',
  '--tone': '#565b5f',
  '--ink': '#ffffff',
  '--ink-soft': '#e4e3cf',
  '--ink-alt': '#ffffff',
  '--accent': '#ffb700',
  '--accent-dim': '#b19e44',
  '--harmonic': '#545b5b',
  '--harmonic-minor': '#6c7f81',
  '--shadow-color': 'rgba(0, 0, 0, 0.4)',
  '--charged':   '#d36464',
  '--active':    '#e2b37e',
  '--calm':      '#7ecdab',
  '--still':     '#8198df',
  '--charged-wash': 'color-mix(in oklch, var(--charged) 15%, var(--base-tone))',
  '--active-wash': 'color-mix(in oklch, var(--active)  15%, var(--base-tone))',
  '--calm-wash': 'color-mix(in oklch, var(--calm)    15%, var(--base-tone))',
  '--still-wash': 'color-mix(in oklch, var(--still)   15%, var(--base-tone))',
};
