// Humo

export const lightThemeColors = {
  '--base-tone': '#ededed',
  '--tone-dim': '#e8e9e9',
  '--tone': '#dee5ed',
  '--ink': '#101624',
  '--ink-soft': '#636a76',
  '--ink-alt': '#ffffff',
  '--accent': '#3679e4',
  '--accent-dim': '#c3c7cb',
  '--harmonic': '#d6d8dc',
  '--harmonic-minor': '#e1e2e4',
  '--charged':   '#d1431f',
  '--active':    '#df8e01',
  '--calm':      '#00ad54',
  '--still':     '#2d5ae1',
  '--charged-wash': 'color-mix(in oklch, var(--charged) 15%, var(--base-tone))',
  '--active-wash': 'color-mix(in oklch, var(--active)  15%, var(--base-tone))',
  '--calm-wash': 'color-mix(in oklch, var(--calm)    15%, var(--base-tone))',
  '--still-wash': 'color-mix(in oklch, var(--still)   15%, var(--base-tone))',
};

export const darkThemeColors = {
  '--base-tone': '#1f2937',
  '--tone-dim': '#242c3c',
  '--tone': '#3b4a61',
  '--ink': '#f3f4f6',
  '--ink-soft': '#9ca3af',
  '--ink-alt': '#ffffff',
  '--accent': '#60a5fa',
  '--accent-dim': '#4b5563',
  '--harmonic': '#374151',
  '--harmonic-minor': '#28303b',
  '--shadow-color': 'rgba(0, 0, 0, 0.4)',
  '--charged': '#f9699a',
  '--active': '#f4c762',
  '--calm': '#9ed999',
  '--still': '#9c81ec',
  '--charged-wash': 'color-mix(in oklch, var(--charged) 15%, var(--base-tone))',
  '--active-wash': 'color-mix(in oklch, var(--active)  15%, var(--base-tone))',
  '--calm-wash': 'color-mix(in oklch, var(--calm)    15%, var(--base-tone))',
  '--still-wash': 'color-mix(in oklch, var(--still)   15%, var(--base-tone))',
};
