// Mar

export const lightThemeColors = {
  '--base-tone': '#c9c4bf',
  '--tone-dim': '#d4d0cc',
  '--tone': '#bbbfd4',
  '--ink': '#212935',
  '--ink-soft': '#657184',
  '--ink-alt': '#ffffff',
  '--accent': '#1c59bd',
  '--accent-dim': '#4874be',
  '--harmonic': '#8f98a6',
  '--harmonic-minor': '#b5bac1',
  '--charged':   '#d1431f',
  '--active':    '#d58b0b',
  '--calm':      '#05bd5e',
  '--still':     '#2d5ae1',
  '--charged-wash': 'color-mix(in oklch, var(--charged) 15%, var(--base-tone))',
  '--active-wash': 'color-mix(in oklch, var(--active)  15%, var(--base-tone))',
  '--calm-wash': 'color-mix(in oklch, var(--calm)    15%, var(--base-tone))',
  '--still-wash': 'color-mix(in oklch, var(--still)   15%, var(--base-tone))',
};

export const darkThemeColors = {
  '--base-tone': '#0f131b',
  '--tone-dim': '#121720',
  '--tone': '#162e48',
  '--ink': '#d3eaf8',
  '--ink-soft': '#6f8fa4',
  '--ink-alt': '#ffffff',
  '--accent': '#4cbef2',
  '--accent-dim': '#3d6178',
  '--harmonic': '#203d5d',
  '--harmonic-minor': '#162738',
  '--charged': '#f9699a',
  '--active': '#f4c762',
  '--calm': '#9ed999',
  '--still': '#9489e1',
  '--charged-wash': 'color-mix(in oklch, var(--charged) 15%, var(--base-tone))',
  '--active-wash': 'color-mix(in oklch, var(--active)  15%, var(--base-tone))',
  '--calm-wash': 'color-mix(in oklch, var(--calm)    15%, var(--base-tone))',
  '--still-wash': 'color-mix(in oklch, var(--still)   15%, var(--base-tone))',
};
