import assert from 'node:assert/strict'
import { chromium } from 'playwright'
import { createServer } from 'vite'

const server = await createServer({ configFile: false, root: process.cwd(), logLevel: 'error', server: { host: '127.0.0.1', port: 0 }, optimizeDeps: { noDiscovery: true } })
let browser
try {
  await server.listen()
  const url = server.resolvedUrls?.local[0]
  if (!url) throw new Error('Vite did not expose a local style-smoke URL')
  browser = await chromium.launch({ headless: true })
  const page = await browser.newPage({ viewport: { width: 1280, height: 800 } })
  await page.goto(new URL('/tests/style-smoke.html', url).href)
  await page.waitForFunction(() => document.documentElement.dataset.styleSmokeReady === 'true')
  const shadowTarget = (name, properties) => page.evaluate(({ name, properties }) => {
    const host = [...document.querySelectorAll('body > div')].find((element) => element.shadowRoot?.querySelector(`[data-probe="${name}"]`))
    const target = host.shadowRoot.querySelector(`[data-probe="${name}"]`)
    const styles = getComputedStyle(target)
    return Object.fromEntries(properties.map((property) => [property, styles.getPropertyValue(property)]))
  }, { name, properties })
  const actual = await page.evaluate(() => {
    const pick = (element, properties) => Object.fromEntries(properties.map((property) => [property, getComputedStyle(element).getPropertyValue(property)]))
    const shadowProbe = (name, properties) => {
      const host = [...document.querySelectorAll('body > div')].find((element) => element.shadowRoot?.querySelector(`[data-probe="${name}"]`))
      const target = host.shadowRoot.querySelector(`[data-probe="${name}"]`)
      return { host: pick(host, ['font-family', 'line-height']), target: pick(target, properties) }
    }
    const shadowTarget = (name, properties) => {
      const host = [...document.querySelectorAll('body > div')].find((element) => element.shadowRoot?.querySelector(`[data-probe="${name}"]`))
      return pick(host.shadowRoot.querySelector(`[data-probe="${name}"]`), properties)
    }
    const modalHost = [...document.querySelectorAll('body > div')].find((element) => element.shadowRoot?.querySelector('[data-probe="modal"]'))
    return {
      generatedGrammarPresent: [...modalHost.shadowRoot.querySelectorAll('style')].some((style) => style.textContent.includes('GENERATED by Ermine adoption/build-css.ts')),
      page: {
        body: pick(document.body, ['font-family', 'margin', 'padding']),
        container: pick(document.querySelector('#page'), ['padding', 'max-width', 'min-height']),
        row: pick(document.querySelector('#row'), ['display', 'flex-direction', 'gap']),
        button: pick(document.querySelector('#button'), ['display', 'padding', 'border-radius', 'background-color']),
        popup: pick(document.querySelector('#popup'), ['width', 'background-color', 'color']),
        optionsPrefix: pick(document.querySelector('#options-prefix'), ['background-color', 'color', 'border-top-color', 'border-top-width', 'border-top-style']),
        optionsPrefixSelected: pick(document.querySelector('#options-prefix-selected'), ['background-color', 'color', 'border-top-color', 'border-top-width', 'border-top-style']),
      },
      modal: shadowProbe('modal', ['display', 'flex-direction', 'width', 'height', 'border-radius', 'overflow']),
      search: {
        view: shadowTarget('search-view', ['display', 'flex-direction', 'height']),
        inputContainer: shadowTarget('search-input-container', ['padding', 'border-bottom-width']),
        input: shadowTarget('search-input', ['padding-top', 'padding-right', 'padding-bottom', 'padding-left']),
        results: shadowTarget('search-results', ['display', 'flex-grow', 'flex-shrink', 'flex-basis', 'max-height', 'overflow-y']),
        item: shadowTarget('search-item', ['display', 'grid-column', 'position']),
        cell: shadowTarget('search-cell', ['padding-top', 'padding-right', 'padding-bottom', 'padding-left']),
        edit: shadowTarget('search-edit', ['position', 'display', 'align-items', 'justify-content', 'padding']),
        footer: shadowTarget('search-footer', ['display', 'justify-content', 'padding']),
        shortcut: shadowTarget('search-shortcut', ['display', 'align-items', 'gap']),
        kbd: shadowTarget('search-kbd', ['position', 'display', 'align-items', 'justify-content']),
      },
      settings: {
        view: shadowTarget('settings-view', ['display', 'flex-direction', 'height', 'overflow-y']),
        group: shadowTarget('settings-group', ['display', 'padding-top', 'padding-right', 'padding-bottom', 'padding-left']),
        label: shadowTarget('settings-label', ['width']),
        rows: shadowTarget('settings-rows', ['width']),
        row: shadowTarget('settings-row', ['display', 'align-items', 'justify-content', 'gap', 'padding-top', 'padding-bottom']),
        appearance: shadowTarget('settings-appearance', ['display', 'align-items', 'gap']),
        seg: shadowTarget('seg-control', ['display', 'position', 'overflow', 'border-radius']),
        prefix: shadowTarget('settings-prefix', ['flex-grow', 'flex-shrink', 'width', 'height', 'display', 'align-items', 'justify-content', 'background-color', 'color', 'border-top-color', 'border-top-width', 'border-top-style']),
        export: shadowTarget('settings-export', ['background-color', 'color', 'border-top-color', 'border-top-width', 'border-top-style']),
      },
      editor: {
        view: shadowTarget('editor-view', ['display', 'flex-direction', 'padding-top', 'padding-right', 'padding-bottom', 'padding-left']),
        form: shadowTarget('editor-form', ['position', 'display', 'flex-direction', 'flex-grow', 'flex-shrink', 'flex-basis', 'gap', 'min-height']),
        topbar: shadowTarget('editor-topbar', ['display', 'align-items', 'justify-content', 'gap']),
        lead: shadowTarget('editor-topbar-lead', ['display', 'align-items', 'gap', 'flex-grow', 'flex-shrink']),
        popout: shadowTarget('editor-popout', ['display', 'align-items', 'justify-content', 'padding']),
        dropdown: shadowTarget('command-suggestions', ['position', 'overflow', 'border-radius']),
        item: shadowTarget('command-suggestion-item', ['display', 'align-items', 'gap', 'padding-top', 'padding-right', 'padding-bottom', 'padding-left', 'background-color']),
        action: shadowTarget('command-suggestion-action', ['display', 'align-items', 'justify-content', 'padding']),
        content: shadowTarget('content-editor', ['display', 'flex-direction', 'flex-grow', 'flex-shrink', 'flex-basis', 'overflow']),
        toolbar: shadowTarget('ce-toolbar', ['display', 'flex-direction', 'flex-wrap', 'align-items', 'gap', 'padding-top', 'padding-right', 'padding-bottom', 'padding-left', 'flex-grow', 'flex-shrink']),
        toolbarBtn: shadowTarget('ce-toolbar-btn', ['display', 'align-items', 'justify-content', 'flex-grow', 'flex-shrink']),
        menu: shadowTarget('ce-style-menu', ['position']),
        dropdown2: shadowTarget('ce-style-dropdown', ['position', 'display', 'flex-direction', 'padding', 'gap']),
        option: shadowTarget('ce-style-option', ['display', 'align-items', 'gap', 'padding-top', 'padding-right', 'padding-bottom', 'padding-left']),
        buttonGroup: shadowTarget('button-group', ['display']),
        cancel: shadowTarget('button-cancel', ['background-color', 'color', 'border-top-color', 'border-top-width', 'border-top-style']),
        save: shadowTarget('button-save', ['background-color', 'color', 'border-top-color', 'border-top-width', 'border-top-style']),
      },
      suggestions: {
        container: shadowProbe('suggestions', ['min-width', 'max-width', 'border-radius', 'overflow', 'font-size']),
        list: shadowTarget('suggestions-list', ['display', 'padding', 'gap']),
        option: shadowTarget('suggestions-option', ['flex-grow', 'flex-shrink', 'padding-top', 'padding-right', 'padding-bottom', 'padding-left', 'background-color', 'color', 'border-color']),
        base: shadowTarget('suggestions-option-base', ['background-color', 'color', 'border-color']),
        footer: shadowTarget('suggestions-footer', ['display', 'gap', 'justify-content']),
      },
      deletion: {
        container: shadowProbe('deletion', ['min-width', 'max-width', 'border-radius']),
        option: shadowTarget('delete-option', ['flex-grow', 'flex-shrink', 'flex-basis', 'max-width']),
      },
    }
  })
  await page.locator('[data-probe="suggestions-option-hover"]').hover()
  await page.waitForTimeout(200)
  actual.suggestions.hoverOnly = await shadowTarget('suggestions-option-hover', ['background-color', 'color', 'border-color'])
  await page.locator('[data-probe="suggestions-option"]').hover()
  await page.waitForTimeout(200)
  actual.suggestions.selectedHover = await shadowTarget('suggestions-option', ['background-color', 'color', 'border-color'])
  const expected = {
  "generatedGrammarPresent": true,
  "page": {
    "body": {
      "font-family": "\"IBM Plex Condensed Light\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif",
      "margin": "0px",
      "padding": "0px"
    },
    "container": {
      "padding": "24px",
      "max-width": "672px",
      "min-height": "800px"
    },
    "row": {
      "display": "flex",
      "flex-direction": "row",
      "gap": "8px"
    },
    "button": {
      "display": "block",
      "padding": "4px 8px",
      "border-radius": "6px",
      "background-color": "rgb(20, 90, 200)"
    },
    "popup": {
      "width": "320px",
      "background-color": "rgb(250, 251, 252)",
      "color": "rgb(20, 21, 22)"
    },
    "optionsPrefix": {
      "background-color": "rgb(250, 251, 252)",
      "color": "rgb(20, 21, 22)",
      "border-top-color": "rgb(160, 161, 162)",
      "border-top-width": "1px",
      "border-top-style": "solid"
    },
    "optionsPrefixSelected": {
      "background-color": "rgb(20, 90, 200)",
      "color": "rgb(254, 254, 254)",
      "border-top-color": "rgb(20, 90, 200)",
      "border-top-width": "1px",
      "border-top-style": "solid"
    }
  },
  "modal": {
    "host": {
      "font-family": "\"IBM Plex Condensed Light\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif",
      "line-height": "24px"
    },
    "target": {
      "display": "flex",
      "flex-direction": "column",
      "width": "600px",
      "height": "560px",
      "border-radius": "8px",
      "overflow": "hidden"
    }
  },
  "search": {
    "view": { "display": "flex", "flex-direction": "column", "height": "558px" },
    "inputContainer": { "padding": "16px", "border-bottom-width": "1px" },
    "input": { "padding-top": "8px", "padding-right": "12px", "padding-bottom": "8px", "padding-left": "12px" },
    "results": { "display": "grid", "flex-grow": "1", "flex-shrink": "1", "flex-basis": "0%", "max-height": "400px", "overflow-y": "auto" },
    "item": { "display": "grid", "grid-column": "1 / -1", "position": "relative" },
    "cell": { "padding-top": "12px", "padding-right": "4px", "padding-bottom": "12px", "padding-left": "12px" },
    "edit": { "position": "absolute", "display": "flex", "align-items": "center", "justify-content": "center", "padding": "4px" },
    "footer": { "display": "flex", "justify-content": "space-between", "padding": "8px" },
    "shortcut": { "display": "inline-flex", "align-items": "center", "gap": "8px" },
    "kbd": { "position": "relative", "display": "flex", "align-items": "center", "justify-content": "center" }
  },
  "settings": {
    "view": { "display": "flex", "flex-direction": "column", "height": "295px", "overflow-y": "auto" },
    "group": {
      "display": "grid",
      "padding-top": "20px",
      "padding-right": "40px",
      "padding-bottom": "20px",
      "padding-left": "40px"
    },
    "label": { "width": "300px" },
    "rows": { "width": "900px" },
    "row": {
      "display": "flex",
      "align-items": "center",
      "justify-content": "space-between",
      "gap": "16px",
      "padding-top": "8px",
      "padding-bottom": "8px"
    },
    "appearance": { "display": "flex", "align-items": "center", "gap": "12px" },
    "seg": { "display": "flex", "position": "relative", "overflow": "hidden", "border-radius": "6px" },
    "prefix": {
      "flex-grow": "0",
      "flex-shrink": "0",
      "width": "32px",
      "height": "32px",
      "display": "flex",
      "align-items": "center",
      "justify-content": "center",
      "background-color": "rgb(235, 236, 237)",
      "color": "rgb(20, 21, 22)",
      "border-top-color": "rgb(160, 161, 162)",
      "border-top-width": "1px",
      "border-top-style": "solid"
    },
    "export": {
      "background-color": "rgb(235, 236, 237)",
      "color": "rgb(20, 21, 22)",
      "border-top-color": "rgb(160, 161, 162)",
      "border-top-width": "1px",
      "border-top-style": "solid"
    }
  },
  "editor": {
    "view": {
      "display": "flex",
      "flex-direction": "column",
      "padding-top": "20px",
      "padding-right": "20px",
      "padding-bottom": "20px",
      "padding-left": "20px"
    },
    "form": {
      "position": "relative",
      "display": "flex",
      "flex-direction": "column",
      "flex-grow": "1",
      "flex-shrink": "1",
      "flex-basis": "0%",
      "gap": "12px",
      "min-height": "0px"
    },
    "topbar": { "display": "flex", "align-items": "center", "justify-content": "space-between", "gap": "16px" },
    "lead": { "display": "flex", "align-items": "center", "gap": "8px", "flex-grow": "0", "flex-shrink": "0" },
    "popout": { "display": "flex", "align-items": "center", "justify-content": "center", "padding": "4px" },
    "dropdown": { "position": "absolute", "overflow": "hidden", "border-radius": "0px 0px 6px 6px" },
    "item": {
      "display": "flex",
      "align-items": "center",
      "gap": "12px",
      "padding-top": "8px",
      "padding-right": "12px",
      "padding-bottom": "8px",
      "padding-left": "12px",
      "background-color": "rgb(220, 221, 222)"
    },
    "action": { "display": "flex", "align-items": "center", "justify-content": "center", "padding": "4px" },
    "content": {
      "display": "flex",
      "flex-direction": "column",
      "flex-grow": "1",
      "flex-shrink": "1",
      "flex-basis": "0%",
      "overflow": "hidden"
    },
    "toolbar": {
      "display": "flex",
      "flex-direction": "row",
      "flex-wrap": "wrap",
      "align-items": "center",
      "gap": "4px",
      "padding-top": "4px",
      "padding-right": "8px",
      "padding-bottom": "4px",
      "padding-left": "8px",
      "flex-grow": "0",
      "flex-shrink": "0"
    },
    "toolbarBtn": { "display": "flex", "align-items": "center", "justify-content": "center", "flex-grow": "0", "flex-shrink": "0" },
    "menu": { "position": "relative" },
    "dropdown2": { "position": "absolute", "display": "flex", "flex-direction": "column", "padding": "4px", "gap": "4px" },
    "option": {
      "display": "flex",
      "align-items": "center",
      "gap": "8px",
      "padding-top": "4px",
      "padding-right": "8px",
      "padding-bottom": "4px",
      "padding-left": "8px"
    },
    "buttonGroup": {
      "display": "flex"
    },
    "cancel": {
      "background-color": "rgb(250, 251, 252)",
      "color": "rgb(20, 21, 22)",
      "border-top-color": "rgb(160, 161, 162)",
      "border-top-width": "1px",
      "border-top-style": "solid"
    },
    "save": {
      "background-color": "rgb(30, 140, 80)",
      "color": "rgb(254, 254, 254)",
      "border-top-color": "rgb(160, 161, 162)",
      "border-top-width": "1px",
      "border-top-style": "solid"
    }
  },
  "suggestions": {
    "container": {
      "host": {
        "font-family": "\"IBM Plex Condensed Light\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif",
        "line-height": "24px"
      },
      "target": {
        "min-width": "200px",
        "max-width": "360px",
        "border-radius": "8px",
        "overflow": "hidden",
        "font-size": "15px"
      }
    },
    "list": {
      "display": "flex",
      "padding": "4px",
      "gap": "4px"
    },
    "option": {
      "flex-grow": "0",
      "flex-shrink": "1",
      "padding-top": "4px",
      "padding-right": "8px",
      "padding-bottom": "4px",
      "padding-left": "8px",
      "background-color": "rgb(220, 221, 222)",
      "color": "rgb(20, 90, 200)",
      "border-color": "rgb(20, 90, 200)"
    },
    "base": {
      "background-color": "rgb(235, 236, 237)",
      "color": "rgb(20, 21, 22)",
      "border-color": "rgb(200, 201, 202)"
    },
    "hoverOnly": {
      "background-color": "rgb(220, 221, 222)",
      "color": "rgb(20, 21, 22)",
      "border-color": "rgb(160, 161, 162)"
    },
    "selectedHover": {
      "background-color": "rgb(220, 221, 222)",
      "color": "rgb(20, 90, 200)",
      "border-color": "rgb(20, 90, 200)"
    },
    "footer": {
      "display": "flex",
      "gap": "12px",
      "justify-content": "flex-end"
    }
  },
  "deletion": {
    "container": {
      "host": {
        "font-family": "\"IBM Plex Condensed Light\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif",
        "line-height": "24px"
      },
      "target": {
        "min-width": "240px",
        "max-width": "360px",
        "border-radius": "8px"
      }
    },
    "option": {
      "flex-grow": "1",
      "flex-shrink": "1",
      "flex-basis": "0%",
      "max-width": "none"
    }
  }
}
  assert.deepEqual(actual, expected)
  console.log('style smoke passed: generated grammar + page + modal/search + settings/editor + suggestions + delete confirmation match their frozen baselines')
} finally {
  await browser?.close()
  await server.close()
}
